{
 "title": "Snort IDS/IPS Dashboard",
 "description": "A Snort IDS/IPS dashboard build on Elastisearch, using data parsed from Graylog.\r\n\r\nBased on the setup from IT Security Labs:\r\n\r\nhttps://www.youtube.com/watch?v=WWitHleGFd8\r\n\r\nAnd the original Security Panel dashboard by Tal Bar-Or:\r\n\r\nhttps://grafana.com/grafana/dashboards/3099",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "datasource", "query": "elasticsearch" },
   { "name": "application_name", "query": "snort" },
   { "name": "source", "query": "pfsense" }
  ]
 },
 "panels": [
  { "title": "Alert Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<center><h1><b>Snort</b></h1></center>"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "High Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "priority:1 AND application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Medium Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "priority:2 AND application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Low Severity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "priority:3 AND application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SSH Threats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "application_name:sshguard",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Alert by Severity",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Low",
     "bucketAggs": [
      {
       "field": "priority",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "3", "type": "count" }
     ],
     "query": "priority:3 AND application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    },
    {
     "alias": "Medium",
     "bucketAggs": [
      {
       "field": "priority",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "3", "type": "count" }
     ],
     "query": "priority:2 AND application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    },
    {
     "alias": "High",
     "bucketAggs": [
      {
       "field": "priority",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "3", "type": "count" }
     ],
     "query": "priority:1 AND application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Alert Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Top Alert Type",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "id": "4",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "Low -", "query": "priority:3" },
         { "label": "Medium -", "query": "priority:2" },
         { "label": "High -", "query": "priority:1" }
        ]
       },
       "type": "filters"
      },
      {
       "fake": true,
       "field": "classification",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "alert_description",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Source IP",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "src_addr",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Destination Port",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "src_port",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Destination IP",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "dst_addr",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Destination Port",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dst_port",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Protocole vs Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Geo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Source by Country",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "src_ip_geo_country",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 9, "x": 3, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      },
      {
       "field": "src_ip_geo_country",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 9, "x": 12, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      },
      {
       "field": "dst_ip_geo_country",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Destination by Country",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dst_ip_geo_country",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Alert Log",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "application_name:${application_name} AND source:${source}",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}